# Generated by Django 2.2.7 on 2019-11-26 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
