# Generated by Django 2.2.7 on 2019-11-27 07:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20191126_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
